###consul服务端口号
server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  ####consul注册中心地址
  cloud:
    consul:
      host: 192.168.0.105
      port: 8500
      discovery:
        hostname: localhost
        service-name: ${spring.application.name}
        prefer-ip-address: true
        ip-address: 192.168.0.108
        ip-address: 192.168.0.108
